### ISSUE TITLE
premis - allow possibilty for makedpx to run before rawaudio

### ISSUE THREAD

**Issue by kieranjol** [kieranjol/IFIscripts#108]
right now it fails in the following ways:
1. This error happens regardless if rawaudio is run when a premisxml file already exists, should be an easy fix:

```
looks like premis already exists?
Traceback (most recent call last):
  File "/Users/admin/ifigit/ifiscripts/rawaudio.py", line 100, in <module>
    xml_info    = make_premis(aeo_raw_extract_wav_dir, items)
  File "/Users/admin/ifigit/ifiscripts/premis.py", line 94, in make_premis
    xml_info = write_objects(source_file, items)   
  File "/Users/admin/ifigit/ifiscripts/premis.py", line 307, in write_objects
    object_identifier_uuid_value.text = root_uuid 
UnboundLocalError: local variable 'root_uuid' referenced before assignment
```
1. makedpx is adding the wav to to the premis representation - rawaudio needs to be able to do this for itself. Should be another easy fix.

**Comment by kieranjol** [comment]
This is no longer relevant as makedpx doesn't do as much any more.
