### ISSUE TITLE
run_loop error in seq2ffv1 on windows Python 3.6.7

### ISSUE THREAD

**Issue by digitensions** [kieranjol/IFIscripts#364]
Hello,

Downloaded the new scripts and started testing on HPZ840 running windows 10 and Python 3.6.7.  Got to the oe1111 entry and hit an error:

C:\Users\MACE\Documents\IFIscripts-master>python seq2ffv1.py -i "T:\COMPLETED\DPX BEING PACKAGED\File\4096 x 3065\Scan01" -o "T:\COMPLETED\DPX BEING PACKAGED\File\4096 x 3065\"
Clairmeta is not installed. DCP options will not function!

**** Who are you?
Press 1,2,3,4,5,6,7,8,9

1. Leanne Ledwidge
2. Gavin Martin
3. Kieran O'Leary
4. Raelene Casey
5. Wentao Ma
6. Raven Cooke
7. Eoin O'Donohoe
8. Yujing Huang
9. Thomas Mc Keon
3

**** Please enter the object entry number of the representation

oe1111
Traceback (most recent call last):
  File "seq2ffv1.py", line 381, in <module>
    main()
  File "seq2ffv1.py", line 378, in main
    run_loop(args)
  File "seq2ffv1.py", line 100, in run_loop
    ififuncs.generate_log(log_name_source, 'seq2ffv1.py started.')
  File "C:\Users\MACE Digital Tech\Documents\IFIscripts-master\ififuncs.py", line 299, in generate_log
    with open(log, "w") as fo:
OSError: [Errno 22] Invalid argument: 'T:\\COMPLETED\\DPX BEING PACKAGED\\File\\4096 x 3065"\\_2019_09_04T13_01_25_seq2ffv1_log.log'

I'll try a PR sometime to add a number 10. :)

**Comment by kieranjol** [comment]
Looks like python can't read the log file, see the double quote at 3065?
That looks kinda weird.. also 3065 height!??
T:\COMPLETED\DPX BEING PACKAGED\File\4096 x 3065"\_2019_09_04T13_01_25_
seq2ffv1_log.log'

**Comment by kieranjol** [comment]
P.s I'll try to recreate later on windows, I've never had the output in the
same folder as the input so I'll need to troubleshoot.
Thanks for the report!

**Comment by digitensions** [comment]
Yeah, 3065 is our lovely unique height... We were getting vertical compression through on the scans and questioned our circles being oval. Unsure how GE4 resolved issue, but this became our scan height. Perhaps I should have a chat about it sometime!

Thanks for " explanation. I'd have missed that completely... No rush on this problem. Just keen to try. Copyit works perfectly on z840! :)

**Comment by kieranjol** [comment]
Hmm, so i can't replicate this with python 3.7.4 on Windows 10..
I made a folder with this path: File\4096 x 3065 but I'm not getting your weirdness with the quotes. 
The script is dying here cos it literally can't open the log file that uses the following filename: https://github.com/kieranjol/IFIscripts/blob/master/seq2ffv1.py#L97 

The first thing I'd try on your local install would be to switch the single quotes here to double quotes (just a long shot, worth a try) and see if it fixes things:
https://github.com/kieranjol/IFIscripts/blob/master/seq2ffv1.py#L97

**Comment by kieranjol** [comment]
And by that I mean, change  `'%s_seq2ffv1_log.log'`  to  `"%s_seq2ffv1_log.log"`

**Comment by digitensions** [comment]
Sorted! Thank you, this is such a massive timesaver for me :) 🤞 it gets to the end

**Comment by kieranjol** [comment]
If it works,I'll make the change and push to master.

**Comment by digitensions** [comment]
Okay, fell over regarding RAWcooked and MediaInfo paths - both fixed. Now we have a new thing following on from generating MD5s. A problem with sipcreator.py possibly? Should I check for the ' to " issue?

Checking total size of input folder
Checking if enough space in destination folder
Generating source manifest
Counting the amount of files to be processed.
Generating MD5 for T:\COMPLETED\DPX BEING PACKAGED\FOR WRAP\25273\Reel 01 of 01\2048 x 1513\ada9ab29-e4de-488d-98ab-f9532abe2aaf_source_mediainfo.xml - 1 of 1
copying file with python/shutil
Traceback (most recent call last):
  File "seq2ffv1.py", line 381, in <module>
    main()
  File "seq2ffv1.py", line 378, in main
    run_loop(args)
  File "seq2ffv1.py", line 154, in run_loop
    judgement = package(objects, object_entry, uuid, source_abspath, args, log_name_source, normalisation_tool, user, rawcooked_logfiles, multi_reeler, current_dir)
  File "seq2ffv1.py", line 312, in package
    sipcreator_log, sipcreator_manifest = sipcreator.main(sipcreator_cmd)
  File "C:\Users\MACE Digital Tech\Documents\IFIscripts-master\sipcreator.py", line 534, in main
    package_update.main(supplement_cmd)
  File "C:\Users\MACE Digital Tech\Documents\IFIscripts-master\package_update.py", line 122, in main
    copyit.main([filenames, args.new_folder])
  File "C:\Users\MACE Digital Tech\Documents\IFIscripts-master\copyit.py", line 670, in main
    log_name_source, rootpos, destination, dirname, args
  File "C:\Users\MACE Digital Tech\Documents\IFIscripts-master\copyit.py", line 195, in copy_dir
    shutil.copy2(source, destination_final_path)
  File "C:\Users\MACE Digital Tech\AppData\Local\Programs\Python\Python36\lib\shutil.py", line 257, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "C:\Users\MACE Digital Tech\AppData\Local\Programs\Python\Python36\lib\shutil.py", line 121, in copyfile
    with open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: 'T:\\COMPLETED\\DPX BEING PACKAGED\\FOR WRAP\\25273\\[ATV Today. 01.02.1978. Police 5 - report on rape of teenage girl] Reel 01 of 01\\2048 x 1513\\oe1111\\ada9ab29-e4de-488d-98ab-f9532abe2aaf\\metadata\\supplemental\\ada9ab29-e4de-488d-98ab-f9532abe2aaf_source_mediainfo.xml'

Super massive thanks :)

**Comment by digitensions** [comment]
The path in Errno 2 is looking for a file that is actually in a different location, found here:
 'T:\COMPLETED\DPX BEING PACKAGED\FOR WRAP\25273\Reel 01 of 01\2048 x 1513\ada9ab29-e4de-488d-98ab-f9532abe2aaf_source_mediainfo.xml'
