### ISSUE TITLE
mergepbcore error

### ISSUE THREAD

**Issue by raecasey** [kieranjol/IFIscripts#365]
mergepbcore is not working for me.

here's the output:
Last login: Thu Sep 26 12:50:54 on ttys005
macminis-mini:~ macmini$ mergepbcore.py -h
Traceback (most recent call last):
  File "/Users/macmini/ifigit/ifiscripts/mergepbcore.py", line 6, in <module>
    import batchaccession
  File "/Users/macmini/ifigit/ifiscripts/batchaccession.py", line 19, in <module>
    import ififuncs
  File "/Users/macmini/ifigit/ifiscripts/ififuncs.py", line 25, in <module>
    from builtins import input
ImportError: No module named builtins
macminis-mini:~ macmini$ 

cheers
R

**Comment by kieranjol** [comment]
Hey - I'm pretty sure that this was resolved by using `pip install future` but if not, let me know.
