### ISSUE TITLE
copyit.py error

### ISSUE THREAD

**Issue by klipska** [kieranjol/IFIscripts#375]
I'm getting the following errors after running copyit.py on windows 10:
`Generating MD5 for E:\PR_Video_for_Archives_collected_2020_02\Documentary Chapters\PioneerOfMedia-YouTube sharing.mov - 2102 of 2103
Generating MD5 for E:\PR_Video_for_Archives_collected_2020_02\Documentary Chapters\SF Symphony at 100 .mov - 2103 of 2103
Traceback (most recent call last):
  File "C:\Users\klipska\AppData\Local\Programs\Python\Python36-32\Scripts\copyit.py", line 725, in <module>
    main(sys.argv[1:])
  File "C:\Users\klipska\AppData\Local\Programs\Python\Python36-32\Scripts\copyit.py", line 654, in main
    manifest_sidecar, log_name_source, manifest, rootpos, args, source
  File "C:\Users\klipska\AppData\Local\Programs\Python\Python36-32\Scripts\copyit.py", line 616, in control_flow
    os.path.dirname(source)
  File "C:\Users\klipska\AppData\Local\Programs\Python\Python36-32\Scripts\copyit.py", line 175, in make_manifest
    text.write(i + '\n')
  File "c:\users\klipska\appdata\local\programs\python\python36-32\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\uf022' in position 108: character maps to <undefined>`

When I try to re-run, it hes issues with the manifest even though it seemed to generate md5s for everything already:
`('There are', 2103, 'files in your source directory', 750, 'in the manifest')`

Any tips for me to try are appreciated!

**Comment by kieranjol** [comment]
Hi!
Looks like a unicode issue. I have a branch that attempts to solve this
issue for irish accents /diacritics and I hope that it would solve your
issue too.
You may have already sent this but a screen shot of any files with
diacritics would help here..

**Comment by kieranjol** [comment]
Seems like this was the mysterious Windows Dot, possibly a translation of the OSX Finder coloured highlight. It tends to gett garbled in general in a windows cmd, usually represented as a question mark or a square. Based on email communication, I believe that removing this dot fixed the issue?
